#!/bin/bash

OUTPUT_FILE=$1
shift
TOOL_A=$1
shift
TOOL_B=$1
shift

DEL_INTERSECT_SIZE="0"
DEL_UNION_SIZE="0"
DEL_TOOL_A_SIZE="0"
DEL_TOOL_B_SIZE="0"
DEL_TOOL_A_UNIQUE="0"
DEL_INTERSECT_SIZE="0"
DEL_TOOL_B_UNIQUE="0"

INS_INTERSECT_SIZE="0"
INS_UNION_SIZE="0"
INS_TOOL_A_SIZE="0"
INS_TOOL_B_SIZE="0"
INS_TOOL_A_UNIQUE="0"
INS_TOOL_B_UNIQUE="0"

DUP_INTERSECT_SIZE="0"
DUP_UNION_SIZE="0"
DUP_TOOL_A_SIZE="0"
DUP_TOOL_B_SIZE="0"
DUP_TOOL_A_UNIQUE="0"
DUP_TOOL_B_UNIQUE="0"

INV_INTERSECT_SIZE="0"
INV_UNION_SIZE="0"
INV_TOOL_A_SIZE="0"
INV_TOOL_B_SIZE="0"
INV_TOOL_A_UNIQUE="0"
INV_TOOL_B_UNIQUE="0"

TRANS_INTERSECT_SIZE="0"
TRANS_UNION_SIZE="0"
TRANS_TOOL_A_SIZE="0"
TRANS_TOOL_B_SIZE="0"
TRANS_TOOL_A_UNIQUE="0"
TRANS_TOOL_B_UNIQUE="0"

for CURR_FILE in $*
do

	readarray -t FILE_LINES < $CURR_FILE

	DEL_ROW=( ${FILE_LINES[1]} )
	DEL_INTERSECT_SIZE=$((DEL_INTERSECT_SIZE+${DEL_ROW[10]}))
	DEL_UNION_SIZE=$((DEL_UNION_SIZE+${DEL_ROW[6]}))
	DEL_TOOL_A_SIZE=$((DEL_TOOL_A_SIZE+${DEL_ROW[7]}))
	DEL_TOOL_B_SIZE=$((DEL_TOOL_B_SIZE+${DEL_ROW[8]}))
	DEL_TOOL_A_UNIQUE=$((DEL_TOOL_A_UNIQUE+${DEL_ROW[9]}))
	DEL_TOOL_B_UNIQUE=$((DEL_TOOL_B_UNIQUE+${DEL_ROW[11]}))

        INS_ROW=( ${FILE_LINES[2]} )
        INS_INTERSECT_SIZE=$((INS_INTERSECT_SIZE+${INS_ROW[10]}))
        INS_UNION_SIZE=$((INS_UNION_SIZE+${INS_ROW[6]}))
        INS_TOOL_A_SIZE=$((INS_TOOL_A_SIZE+${INS_ROW[7]}))
        INS_TOOL_B_SIZE=$((INS_TOOL_B_SIZE+${INS_ROW[8]}))
        INS_TOOL_A_UNIQUE=$((INS_TOOL_A_UNIQUE+${INS_ROW[9]}))
        INS_TOOL_B_UNIQUE=$((INS_TOOL_B_UNIQUE+${INS_ROW[11]}))


        DUP_ROW=( ${FILE_LINES[3]} )
        DUP_INTERSECT_SIZE=$((DUP_INTERSECT_SIZE+${DUP_ROW[10]}))
        DUP_UNION_SIZE=$((DUP_UNION_SIZE+${DUP_ROW[6]}))
        DUP_TOOL_A_SIZE=$((DUP_TOOL_A_SIZE+${DUP_ROW[7]}))
        DUP_TOOL_B_SIZE=$((DUP_TOOL_B_SIZE+${DUP_ROW[8]}))
        DUP_TOOL_A_UNIQUE=$((DUP_TOOL_A_UNIQUE+${DUP_ROW[9]}))
        DUP_TOOL_B_UNIQUE=$((DUP_TOOL_B_UNIQUE+${DUP_ROW[11]}))


        INV_ROW=( ${FILE_LINES[4]} )
        INV_INTERSECT_SIZE=$((INV_INTERSECT_SIZE+${INV_ROW[10]}))
        INV_UNION_SIZE=$((INV_UNION_SIZE+${INV_ROW[6]}))
        INV_TOOL_A_SIZE=$((INV_TOOL_A_SIZE+${INV_ROW[7]}))
        INV_TOOL_B_SIZE=$((INV_TOOL_B_SIZE+${INV_ROW[8]}))
        INV_TOOL_A_UNIQUE=$((INV_TOOL_A_UNIQUE+${INV_ROW[9]}))
        INV_TOOL_B_UNIQUE=$((INV_TOOL_B_UNIQUE+${INV_ROW[11]}))

        TRANS_ROW=( ${FILE_LINES[5]} )
        TRANS_INTERSECT_SIZE=$((TRANS_INTERSECT_SIZE+${TRANS_ROW[10]}))
        TRANS_UNION_SIZE=$((TRANS_UNION_SIZE+${TRANS_ROW[6]}))
        TRANS_TOOL_A_SIZE=$((TRANS_TOOL_A_SIZE+${TRANS_ROW[7]}))
        TRANS_TOOL_B_SIZE=$((TRANS_TOOL_B_SIZE+${TRANS_ROW[8]}))
        TRANS_TOOL_A_UNIQUE=$((TRANS_TOOL_A_UNIQUE+${TRANS_ROW[9]}))
        TRANS_TOOL_B_UNIQUE=$((TRANS_TOOL_B_UNIQUE+${TRANS_ROW[11]}))
done


DEL_TOOL_A_PRECISION=$(awk -v INTERSECT="$DEL_INTERSECT_SIZE" -v ASIZE="$DEL_TOOL_A_SIZE" 'BEGIN { printf "%.2f", INTERSECT/ASIZE*100 }' </dev/null)
DEL_TOOL_B_PRECISION=$(awk -v INTERSECT="$DEL_INTERSECT_SIZE" -v BSIZE="$DEL_TOOL_B_SIZE" 'BEGIN { printf "%.2f", INTERSECT/BSIZE*100 }' </dev/null)
DEL_JACCARD=$(awk -v INTERSECT="$DEL_INTERSECT_SIZE" -v UNION="$DEL_UNION_SIZE" 'BEGIN { printf "%.2f", INTERSECT/UNION*100 }' </dev/null)

INS_TOOL_A_PRECISION=$(awk -v INTERSECT="$INS_INTERSECT_SIZE" -v ASIZE="$INS_TOOL_A_SIZE" 'BEGIN { printf "%.2f", INTERSECT/ASIZE*100 }' </dev/null)
INS_TOOL_B_PRECISION=$(awk -v INTERSECT="$INS_INTERSECT_SIZE" -v BSIZE="$INS_TOOL_B_SIZE" 'BEGIN { printf "%.2f", INTERSECT/BSIZE*100 }' </dev/null)
INS_JACCARD=$(awk -v INTERSECT="$INS_INTERSECT_SIZE" -v UNION="$INS_UNION_SIZE" 'BEGIN { printf "%.2f", INTERSECT/UNION*100 }' </dev/null)

DUP_TOOL_A_PRECISION=$(awk -v INTERSECT="$DUP_INTERSECT_SIZE" -v ASIZE="$DUP_TOOL_A_SIZE" 'BEGIN { printf "%.2f", INTERSECT/ASIZE*100 }' </dev/null)
DUP_TOOL_B_PRECISION=$(awk -v INTERSECT="$DUP_INTERSECT_SIZE" -v BSIZE="$DUP_TOOL_B_SIZE" 'BEGIN { printf "%.2f", INTERSECT/BSIZE*100 }' </dev/null)
DUP_JACCARD=$(awk -v INTERSECT="$DUP_INTERSECT_SIZE" -v UNION="$DUP_UNION_SIZE" 'BEGIN { printf "%.2f", INTERSECT/UNION*100 }' </dev/null)

INV_TOOL_A_PRECISION=$(awk -v INTERSECT="$INV_INTERSECT_SIZE" -v ASIZE="$INV_TOOL_A_SIZE" 'BEGIN { printf "%.2f", INTERSECT/ASIZE*100 }' </dev/null)
INV_TOOL_B_PRECISION=$(awk -v INTERSECT="$INV_INTERSECT_SIZE" -v BSIZE="$INV_TOOL_B_SIZE" 'BEGIN { printf "%.2f", INTERSECT/BSIZE*100 }' </dev/null)
INV_JACCARD=$(awk -v INTERSECT="$INV_INTERSECT_SIZE" -v UNION="$INV_UNION_SIZE" 'BEGIN { printf "%.2f", INTERSECT/UNION*100 }' </dev/null)

TRANS_TOOL_A_PRECISION=$(awk -v INTERSECT="$TRANS_INTERSECT_SIZE" -v ASIZE="$TRANS_TOOL_A_SIZE" 'BEGIN { printf "%.2f", INTERSECT/ASIZE*100 }' </dev/null)
TRANS_TOOL_B_PRECISION=$(awk -v INTERSECT="$TRANS_INTERSECT_SIZE" -v BSIZE="$TRANS_TOOL_B_SIZE" 'BEGIN { printf "%.2f", INTERSECT/BSIZE*100 }' </dev/null)
TRANS_JACCARD=$(awk -v INTERSECT="$TRANS_INTERSECT_SIZE" -v UNION="$TRANS_UNION_SIZE" 'BEGIN { printf "%.2f", INTERSECT/UNION*100 }' </dev/null)


echo "#ToolA	ToolB	Type	Jaccard%	PrecA%	PrecB%	Union	SizeA	SizeB	UniqueA	Intersect	UniqueB" > $OUTPUT_FILE

#Append the entry for the pair of tools designated by arguments
echo "$TOOL_A	$TOOL_B	DEL	${DEL_JACCARD}%	${DEL_TOOL_A_PRECISION}%	${DEL_TOOL_B_PRECISION}%	$DEL_UNION_SIZE	$DEL_TOOL_A_SIZE	$DEL_TOOL_B_SIZE	$DEL_TOOL_A_UNIQUE	$DEL_INTERSECT_SIZE	$DEL_TOOL_B_UNIQUE" >> "$OUTPUT_FILE"
echo "$TOOL_A	$TOOL_B	INS	${INS_JACCARD}%	${INS_TOOL_A_PRECISION}%	${INS_TOOL_B_PRECISION}%	$INS_UNION_SIZE	$INS_TOOL_A_SIZE	$INS_TOOL_B_SIZE	$INS_TOOL_A_UNIQUE	$INS_INTERSECT_SIZE	$INS_TOOL_B_UNIQUE" >> "$OUTPUT_FILE"
echo "$TOOL_A	$TOOL_B	DUP	${DUP_JACCARD}%	${DUP_TOOL_A_PRECISION}%	${DUP_TOOL_B_PRECISION}%	$DUP_UNION_SIZE	$DUP_TOOL_A_SIZE	$DUP_TOOL_B_SIZE	$DUP_TOOL_A_UNIQUE	$DUP_INTERSECT_SIZE	$DUP_TOOL_B_UNIQUE" >> "$OUTPUT_FILE"
echo "$TOOL_A	$TOOL_B	INV	${INV_JACCARD}%	${INV_TOOL_A_PRECISION}%	${INV_TOOL_B_PRECISION}%	$INV_UNION_SIZE	$INV_TOOL_A_SIZE	$INV_TOOL_B_SIZE	$INV_TOOL_A_UNIQUE	$INV_INTERSECT_SIZE	$INV_TOOL_B_UNIQUE" >> "$OUTPUT_FILE"
echo "$TOOL_A	$TOOL_B	TRANS	${TRANS_JACCARD}%	${TRANS_TOOL_A_PRECISION}%	${TRANS_TOOL_B_PRECISION}%	$TRANS_UNION_SIZE	$TRANS_TOOL_A_SIZE	$TRANS_TOOL_B_SIZE	$TRANS_TOOL_A_UNIQUE	$TRANS_INTERSECT_SIZE	$TRANS_TOOL_B_UNIQUE" >> "$OUTPUT_FILE"
