#!/bin/bash

INPUT_FILE=$1
OUTPUT_FILE=$2

echo "Converting $INPUT_FILE BED intervals to VCF format..."

readarray INDEX_ARR < $INPUT_FILE
ARR_LEN="${#INDEX_ARR[@]}"
VCF_ARR=()

BND_COUNT=1
for((EACH_INDEX=0;EACH_INDEX<ARR_LEN;EACH_INDEX++)) do
        CURR_ROW_ARR=( ${INDEX_ARR[$EACH_INDEX]} )

        REF_CHR=${CURR_ROW_ARR[0]}
        REF_START=${CURR_ROW_ARR[1]}
        REF_END=${CURR_ROW_ARR[2]}

        SV_LEN=$((REF_END-REF_START))
        #SV_TYPE="BND"
	SV_TYPE="DEL:TRANS"

        #VCF_ARR+=("$REF_CHR	$REF_START	${SV_TYPE}.${BND_COUNT}	N	N	.	PASS	SVTYPE=$SV_TYPE;END=$REF_START;TRANSSTART=$REF_START;TRANSEND=$REF_END;MATEID=${SV_TYPE}.$((BND_COUNT+1))	GT:DP	./.:.")
        #BND_COUNT=$((BND_COUNT+1))
        #VCF_ARR+=("$REF_CHR	$REF_END	${SV_TYPE}.${BND_COUNT}	N	N	.	PASS	SVTYPE=$SV_TYPE;END=$REF_END;TRANSSTART=$REF_START;TRANSEND=$REF_END;MATEID=${SV_TYPE}.$((BND_COUNT-1))	GT:DP	./.:.")
        #BND_COUNT=$((BND_COUNT+1))
	VCF_ARR+=("$REF_CHR	$REF_START	${SV_TYPE}.${BND_COUNT}	N	N	.	PASS	SVTYPE=$SV_TYPE;END=$REF_START;TRANSSTART=$REF_END;SVLEN=$SV_LEN	GT:DP	./.:.")
	BND_COUNT=$((BND_COUNT+1))
done

printf "%s\n" "${VCF_ARR[@]}" >> $OUTPUT_FILE
